version: '3.7'
services:
  frontend:
    build: ./frontend
    ports:
      - '5173:80'
  backend:
    build: ./backend
    ports:
      - '5000:5000'
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=./realm-export.json
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    ports:
      - '8080:8080'
    command:
      - '-Dkeycloak.migration.action=import'
      - '-Dkeycloak.migration.provider=singleFile'
      - '-Dkeycloak.migration.file=/tmp/realm-export.json'
      - start-dev
